add arm64 support
openebs/rawfile-localpv pull request #13
Opened 2022-06-29 05:31 UTC by odidev

The following file has been created and modified:

Added support for arm64 in .travis.yml to make docker images and publish them on docker hub.

**Note:** I have not added the e2e-testing for the arm64 platform because e2e-testing [requires minikube](https://github.com/odidev/rawfile-localpv/blob/0eb4eefd13aca1b3dd5a3e102ec43c1b91509393/.ci/e2e-test/setup.sh#L13) to run on travis for arm64 platform. And travisCI does not support minikube on the arm64 platform. There is an [open issue](https://github.com/kubernetes/minikube/issues/11845) for this in kubernetes/minikube.

Signed-off-by: odidev odidev@puresoftware.com

2022-07-27 07:06 UTC, odidev commented
Hi Team,
A gentle reminder to take a look at the above changes.

2022-07-27 08:45 UTC, semekh commented on .travis.yml
> +      script: ./.ci/publish.sh
Looks like a code duplication to me. Do you think we could avoid that somehow?

2022-07-27 08:47 UTC, semekh requested changes
Thanks for your contribution. Generally LGTM, but it'd be great if we could avoid the code duplication.

2022-09-29 05:54 UTC, odidev commented
> Looks like a code duplication to me. Do you think we could avoid that somehow? 

I think we need to go with this only because when I try to reduce the duplication it does not run for all the stages.

2022-10-19 12:05 UTC, odidev commented
Hi Team,
Adding a gentle reminder to take a look at the above changes.

2025-03-02 19:29 UTC, mhkarimi1383 commented
@tiagolobocastro 
I think we can close this since we want to migrate to GitHub Actions (https://github.com/openebs/rawfile-localpv/issues/41)

2025-03-05 03:51 UTC, tiagolobocastro commented
> @tiagolobocastro I think we can close this since we want to migrate to GitHub Actions (#41)

Yes, I can add arm64 from the getgo to GitHub Actions.

2025-03-05 06:13 UTC, closed without merging